// Generated by Wrangler on Wed Jul 17 2024 14:59:51 GMT-0700 (Pacific Daylight Time)
// by running `wrangler -j types`

interface Env {
	DOCSEARCH_APP_ID: string;
	DOCSEARCH_API_KEY: string;
	DOCSEARCH_INDEX_NAME: string;
}
