-- Migration number: 0001 	 2024-11-15T19:40:10.789Z
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE articles (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT,
  userId INTEGER NOT NULL,
  status TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);