// Generated by Wrangler on Mon Jul 22 2024 14:04:46 GMT-0700 (Pacific Daylight Time)
// by running `wrangler -j types`

interface Env {
	APP_KEY: string;
	CHANNELS: DurableObjectNamespace;
	REMIX_CMS_MEDIA: R2Bucket;
	DB: D1Database;
	QUEUE: Queue;
}
