// Generated by Wrangler on Tue Jul 16 2024 16:00:25 GMT-0700 (Pacific Daylight Time)
// by running `wrangler -j types`

interface Env {
	CHANNELS: DurableObjectNamespace;
	REMIX_CMS_MEDIA: R2Bucket;
	DB: D1Database;
	QUEUE: Queue;
}
