// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_KEY: string;
	CHANNELS: DurableObjectNamespace /* Channel from remix-cms */;
	REMIX_CMS_MEDIA: R2Bucket;
	DB: D1Database;
	QUEUE: Queue;
}
