import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { compileMigrations } from "../cli/migrate";
import { withFileSystem } from "./utils";

describe("compileMigrations", () => {
  const date = new Date();

  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(date);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("compiles a migration to SQL", async () => {
    await withFileSystem(
      {
        "app/migrations/0000_create_users_table.ts": `import { Schema } from 'superflare';
      export default function () {
        return Schema.create("users", (builder) => {
          builder.increments("id");
          builder.string("email");
        });
      }`,
      },
      async (rootPath) => {
        await compileMigrations(
          join(rootPath, "app", "migrations"),
          join(rootPath, "migrations")
        );

        const sql = await readFile(
          join(rootPath, "migrations", "0000_create_users_table.sql"),
          "utf-8"
        );
        const timestamp = new Date().toISOString();
        expect(sql).toEqual(
          `-- Migration number: 0000 	 ${timestamp}
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL
);`
        );
      }
    );
  });

  it("compiles a migration with multiple Schema returns to SQL", async () => {
    await withFileSystem(
      {
        "app/migrations/0000_create_tables.ts": `import { Schema } from 'superflare';
      export default function () {
        return [
          Schema.create("users", (builder) => {
            builder.increments("id");
            builder.string("email");
          }),
          Schema.create("posts", (builder) => {
            builder.increments("id");
            builder.string("title");
          }),
        ];
      }`,
      },
      async (rootPath) => {
        await compileMigrations(
          join(rootPath, "app", "migrations"),
          join(rootPath, "migrations")
        );

        const sql = await readFile(
          join(rootPath, "migrations", "0000_create_tables.sql"),
          "utf-8"
        );
        const timestamp = new Date().toISOString();
        expect(sql).toEqual(
          `-- Migration number: 0000 	 ${timestamp}
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL
);`
        );
      }
    );
  });
});
